### ISSUE TITLE
apt-key setup is deprecated

### ISSUE THREAD

**Issue by MarshallAsch** [compscidr/iac#44]
the method used to add the apt keys has been dreprecated. the key should be placed in `/etc/apt/keyrings/` instead. 

This is specificly an issue with docker and ansible (based on the portions I ran).

**Comment by compscidr** [comment]
For installing docker, I'm using the community role here: https://github.com/nickjj/ansible-docker - it looks like it uses the ansible `builtin.apt_key` for it:
https://github.com/nickjj/ansible-docker/blob/master/tasks/main.yml#L40

Do you have an example of how to get the key where it needs to be? If so I can make a PR to that repo - the guy is pretty responsive, I have another PR in progress there related to an edge case when upgrading from ubuntu 20.04 to 22.04. (otherwise feel free to make a PR there yourself).

For the ansible part, I'll probably just use `python3 -m pip install ansible` in my readme instead of using the ppa repo. That being said, I need to figure out this key thing, its annoying when I run `apt update`. Looks like:
- keybase
- docker
- signal
- ansible
- slack
- golang

All suffer from the same issue in my setup. Looks like all of them use `ansible.builtin.apt_key:`

**Comment by compscidr** [comment]
Looks like someone else submitted a PR to the docker community role: https://github.com/nickjj/ansible-docker/pull/123 for the fix, I'll see if there's a way I can apply similar fixes wherever else I can.

**Comment by compscidr** [comment]
okay seems like this is mostly all fixed across the repo now
